[package]
name = "pikemon_client"
version = "0.0.0"
authors = ["Michael Chesser"]

[[bin]]
name = "pikemon_client"

[dependencies.common]
path = "../common"

[dependencies.gb_emu]
git = "https://github.com/quvarxa/gb_emu.git"

[dependencies.sdl2]
# Change to https://github.com/AngryLawyer/rust-sdl2 when fixes are merged
git = "https://github.com/bitonic/rust-sdl2.git"

[dependencies]
rustc-serialize = "*"
clock_ticks = "*"
