[package]
name = "pikemon_server"
version = "0.0.1"
authors = ["Michael Chesser"]
edition = "2021"

[dependencies]
network_common = { path = "../network_common" }
interface = { path = "../interface" }
crossbeam-channel = "0.5.6"
serde_json = "1.0.85"
