[package]
name = "pikemon_server"
version = "0.0.1"
authors = ["Michael Chesser"]

[dependencies.network_common]
path = "../network_common"

[dependencies.interface]
path = "../interface"

[dependencies]
rustc-serialize = "0.3"
