[package]
name = "pikemon_server"
version = "0.0.0"
authors = ["Michael Chesser"]

[[bin]]
name = "pikemon_server"

[dependencies.network_common]
path = "../network_common"

[dependencies.interface]
path = "../interface"

[dependencies]
rustc-serialize = "*"
