[package]
name = "interface"
version = "0.0.0"
authors = ["Michael Chesser"]
edition = "2021"

[dependencies]
gb_emu = { git = "https://github.com/mchesser/gb_emu" }
serde = { version = "1.0.145", features = ["derive"] }
