[package]
name = "network_common"
version = "0.0.0"
authors = ["Michael Chesser"]
edition = "2021"

[dependencies]
interface = { path = "../interface" }
serde = { version = "1.0.145", features = ["derive"] }
